---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app-backend-prod
  name: my-app-backend-prod
  namespace: my-app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-backend-prod
  template:
    metadata:
      labels:
        app: my-app-backend-prod
    spec:
      containers:
        - image: vovinet/13-kubernetes-config_backend
          imagePullPolicy: IfNotPresent
          name: backend
          envFrom:
          - configMapRef:
              name: cs-backend
      terminationGracePeriodSeconds: 30
