kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logs-describe-role
  namespace: app-namespace
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]