all:
  hosts:
    node1:
      ansible_host: 62.84.127.162
      ip: 10.12.4.25
      ansible_user: ubuntu
    node2:
      ansible_host: 62.84.127.138
      ip: 10.12.4.5
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
