---
apiVersion: v1
kind: Service
metadata:
  name: my-app-stage
  namespace: my-app-stage
spec:
  ports:
    - name: web
      port: 8000
      targetPort: 80
    - name: backend
      port: 9000
  selector:
    app: my-app

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configset-env
  namespace: my-app-stage
data:
  DATABASE_URL: postgres://postgres:postgres@db-stage:5432/news
  BASE_URL: http://my-app-stage:9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
  namespace: my-app-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: vovinet/13-kubernetes-config_frontend
          imagePullPolicy: IfNotPresent
          name: frontend
          envFrom:
          - configMapRef:
              name: configset-env
        - image: vovinet/13-kubernetes-config_backend
          imagePullPolicy: IfNotPresent
          name: backend
          envFrom:
          - configMapRef:
              name: configset-env
      terminationGracePeriodSeconds: 30
