apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello-node
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: hello-tcp
  selector:
    app: hello-node
